# Reusable vars
x-var:
  - &POSTGRES_USER
    postgres
  - &POSTGRES_PASSWORD
    default
  - &POSTGRES_DATABASE
    postgres

# Reusable envars for postgres
x-postgres-vars: &postgres-vars
  POSTGRES_HOST: database
  POSTGRES_USER: *POSTGRES_USER
  POSTGRES_PASSWORD: *POSTGRES_PASSWORD
  POSTGRES_DATABASE: *POSTGRES_DATABASE

services:
  database:
    image: postgis/postgis:17-3.5 # Updated to PostgreSQL 17 with PostGIS 3.4
    container_name: database
    environment:
      <<: *postgres-vars
    healthcheck:
      test: ["CMD", "pg_isready", "-U", *POSTGRES_USER]
    ports: ["5432:5432"]

  migrations:
    image:  ${FLYWAY_IMAGE:-flyway/flyway:11-alpine}
    container_name: migrations
    command: info migrate info
    volumes: ["./migrations/sql:/flyway/sql:ro"]
    environment:
      FLYWAY_URL: jdbc:postgresql://database:5432/postgres
      FLYWAY_USER: *POSTGRES_USER
      FLYWAY_PASSWORD: *POSTGRES_PASSWORD
      FLYWAY_BASELINE_ON_MIGRATE: true
      FLYWAY_DEFAULT_SCHEMA: app
    depends_on:
      database:
        condition: service_healthy
  schemaspy:
    image: schemaspy/schemaspy:6.2.4
    profiles: ["schemaspy"]
    container_name: schemaspy
    command: -t pgsql11 -db postgres -host database -port 5432 -u postgres -p default -schemas app
    depends_on:
      migrations:
        condition: service_completed_successfully
    volumes: ["./output:/output"]

  backend:
    container_name: backend
    depends_on:
      migrations:
        condition: service_completed_successfully
    environment:
      <<: *postgres-vars
      NODE_ENV: development
      PORT: 3001
    image: ${BACKEND_IMAGE:-backend}
    build:
      context: ./backend
    ports: ["3001:3001"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api"]
    working_dir: "/app"

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    environment:
      VITE_BACKEND_URL: http://backend:3001
      VITE_PORT: 3000
      NODE_ENV: development
      LOG_LEVEL: debug
    image: ${FRONTEND_IMAGE:-frontend}
    ports: ["3000:3000"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
    working_dir: "/app"
    depends_on:
      backend:
        condition: service_started
