name: .Destroy Stack

on:
  workflow_call:
    inputs:
      ### Required
      environment_name:
        description: 'The name of the environment to deploy to'
        required: true
        default: 'dev'
        type: string
      command:
        description: 'The terragrunt command to run'
        default: 'destroy'
        required: false
        type: string
      tag:
        description: 'The tag of the containers to deploy'
        default: 'latest'
        type: string
        required: false
      app_env:
        required: false
        type: string
        description: 'The APP env separates between AWS ENV and Actual APP, since AWS dev is where PR, and TEST is deployed'
env:
    AWS_REGION: ca-central-1
permissions:
  id-token: write # This is required for requesting the JWT
  contents: write # This is required for actions/checkout
jobs:
  stack-prefix:
    name: Stack Prefix
    uses: ./.github/workflows/.stack-prefix.yml
  api:
    name: Destroy API
    needs: [stack-prefix]
    uses: ./.github/workflows/.deployer.yml
    with:
      environment_name: ${{ inputs.environment_name }}
      command: ${{ inputs.command }}
      tag: ${{ inputs.tag }}
      app_env: ${{ inputs.app_env }}
      working_directory: api
      stack_prefix: ${{ needs.stack-prefix.outputs.stack_prefix }}
    secrets: inherit
  db:
    name: Destroy Database
    needs: [stack-prefix, api]
    uses: ./.github/workflows/.deployer.yml
    with:
      environment_name: ${{ inputs.environment_name }}
      command: ${{ inputs.command }}
      working_directory: database
      app_env: ${{ inputs.app_env }}
      stack_prefix: ${{ needs.stack-prefix.outputs.stack_prefix }}
    secrets: inherit

  cloudfront:
    name: Destroy Cloudfront
    needs: [stack-prefix]
    uses: ./.github/workflows/.deployer.yml
    with:
      environment_name: ${{ inputs.environment_name }}
      command: ${{ inputs.command }}
      tag: ${{ inputs.tag }}
      app_env: ${{ inputs.app_env }}
      working_directory: frontend
      stack_prefix: ${{ needs.stack-prefix.outputs.stack_prefix }}
    secrets: inherit
  
